version: "2.3"
services:
  keycloak-container:
    image: jboss/keycloak:12.0.4
    command:
      -Djboss.socket.binding.port-offset=200
    restart: always
    environment:
      KEYCLOAK_USER: admin2
      KEYCLOAK_PASSWORD: test
    ports:
      - 8280:8280
    networks:
      - turreta_network
networks:
  turreta_network:
    driver: bridge
